version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - APP_KEY=base64:+dmE+/Xxp+IxQi17kZrVTo8IF3448YwAlfeXBRDV8qE=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
