version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=production
      - APP_KEY=base64:your-app-key-here
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
